networks: { intr: { external: true } }
volumes: { traefik2_acme_data: { driver: "local" } }
services:
  traefik:
    image: traefik:v3
    restart: always
    logging:
      driver: "json-file"
      options: { max-size: "100k", max-file: "3" }
    ports:
      - 80:80
      - 443:443
      - 2002:8080
      - 2001:2001
    networks: [ "intr" ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik2_acme_data:/traefik_acme
      - ./conf:/etc/traefik
    environment:
      - BASE_URL
